### ISSUE TITLE
How to subscribe for events ?

### ISSUE THREAD

**Issue by hammersharkfish** [WalletConnect/WalletConnectSharp#26]
How can we subscribe to a "'disconnect" event ? 
Could we get some working examples for subscribing to events ?  

Thank you .

**Comment by ecp4224** [comment]
There are many event handlers in the `WalletConnectSession` class. These include

* OnSessionConnect
* OnSessionCreated
* OnSessionResumed
* OnSessionDisconnect
* OnSend
* SessionUpdated

You are most likely looking for the `OnSessionDisconnect` event. Here is an example usage of the event handle:

```csharp
var session = new WalletConnectSession(....);

session.OnSessionDisconnect += delegate(object? sender, EventArgs eventArgs)
{
    Console.WriteLine("Session disconnected");
};
```

**Please note the following about the `OnSessionDisconnect` event handler**

* The `EventArgs` provided are not typed, however the `object sender` will always be of type `WalletConnectSession`. It is not explicitly given because the session is considered stale and should not be used anymore.
* The event is only triggered in two cases
    - The `DisconnectSession` function was invoked
    - The session failed to be created (either because of an error or because the user did not approve
    - The session was updated by the wallet and the wallet disconnected the session

The event is **NOT** triggered when
* The wallet deletes the session data itself without sending a session update
* The transport (websocket, socket.io, etc..) layer has disconnected
* The session has gone stale

**Comment by monkjuice** [comment]
hey @ecp4224 

Is SessionUpdated currently supported?

It seems like the chainId is always set to the one the user connected his wallet with.

This can be checked when calling `provider.ChainId;` after changing the wallets network

**Comment by ecp4224** [comment]
@monkjuice `SessionUpdated` is currently being used. Like with other events however, this event is only triggered if the wallet actually sends the `wc_sessionUpdate` JSON RPC request

**Comment by ecp4224** [comment]
@monkjuice  Some bugs surrounding the `SessionUpdated` event have been fixed in the latest commits in main.

**Comment by gigajuwels** [comment]
this is a v1 issue
